platform :ios, '14.0'

target 'FirebaseStarterKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for FirebaseStarterKit

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
  pod 'Firebase/Storage'
  pod 'Firebase/Firestore'
  pod 'GoogleMaps', '7.2.0'
  pod 'GooglePlaces', '7.1.0'
  
end
